### ISSUE TITLE
How to remove the badge number after notifications are read.?

### ISSUE THREAD

**Issue by SenthilKaliathan** [JaviSoto/JSBadgeView#20]
Can you please help me out how to reset the badge count and remove the view.?
I have tried something like this, But it didn't worked out.
        badgeView.badgeText = @"";    or           badgeView.badgeText = @"0"

**Comment by deanq** [comment]
This doesn't work.

**Comment by JaviSoto** [comment]
What doesn't work? Would you mind elaborating on the behavior you're seeing?

**Comment by deanq** [comment]
Never mind. I was previously just using the `initWithParentView` convenience. The general use of this adds the badge view into the parent view, and if you are not referencing it properly, then you can't just "hide" it. I had to create a custom UIButton class (in my case) in order to reference the badgeView object, thus giving me control on updating it for later use.

**Comment by seecoolguy** [comment]
+deanq can you post a short example on what you did?
